repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
    language_version: python3.11

- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:  
  - id: docformatter
    args: ["--in-place", "--style=pep257", "--style=numpydoc"]
    exclude: (venv/|docs/)

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    language_version: python3.11
    exclude: (venv/|docs/)

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    language_version: python3.11
    exclude: (venv/|docs/)
    additional_dependencies: [flake8-docstrings, flake8-bugbear]
    args: [--output-file=flake8-report.txt, --exit-zero]

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
  - id: pylint
    language_version: python3.11
    exclude: (venv/|docs/)
    args: [--output=pylint-report.txt, --exit-zero]

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.942
#   hooks:
#   - id: mypy
#     language_version: python3.11
#     exclude: (venv/|docs/)
#     args: [src, --explicit-package-bases]

# - repo: https://github.com/PyCQA/bandit
#   rev: 1.7.8
#   hooks:
#   - id: bandit
#     language_version: python3.11
#     exclude: (venv/|docs/)