generate_data:
  max_translation: 768
  edges: [288, 2016,288, 2016]
  train:
    events: 200
    simulation:
      dataset: simulation
      valid_indexes: [0, 1, 2, 3]
      max_events: 10
    noise:
      dataset: noise
      valid_indexes: [0, 1, 2, 3]
  test:
    events: 5
    simulation:
      dataset: simulation
      valid_indexes: [0, 1, 2, 3]
      max_events: 10
    noise:
      dataset: noise
      valid_indexes: [0, 1, 2, 3]
  validation:
    events: 5
    simulation:
      dataset: simulation
      valid_indexes: [0, 1, 2, 3]
      max_events: 10
    noise:
      dataset: noise
      valid_indexes: [0, 1, 2, 3]