name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          poetry install --with dev
          poetry run pre-commit install

      - name: Set MYPYPATH
        run: |
          echo "MYPYPATH=src" >> $GITHUB_ENV

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files